/** EduNexus UI direction: Atelier de progression — préférences visibles, persistantes et accessibles sans dépendance backend. */
import { computed, ref } from "vue";

export type Locale = "fr" | "en";
export type Theme = "light" | "dark";

const messages: Record<Locale, Record<string, string>> = {
  fr: {
    "nav.home": "Accueil", "nav.path": "Mon parcours", "nav.revise": "Réviser", "nav.practice": "Exercices", "nav.quiz": "Quiz", "nav.progress": "Progression", "nav.tutor": "Tuteur IA", "nav.sources": "Mes sources", "nav.settings": "Réglages",
    "nav.start": "Commencer", "nav.train": "S’entraîner", "nav.explore": "Explorer", "nav.space": "Espace",
    "app.workshop": "Atelier d’apprentissage", "app.sourcesReady": "Vos sources sont prêtes", "app.localModel": "Ollama local", "app.sources": "Sources", "app.localData": "Vos données restent locales.",
    "app.loadingSubject": "Chargement de votre matière…", "app.loadingWorkshop": "Chargement de votre atelier d’apprentissage…", "nexus.aria": "Vos sources alimentent des notions, qui alimentent votre prochaine étape.", "nexus.sources": "Sources", "nexus.concepts": "Notions", "nexus.activeStep": "Étape active",
    "preferences.light": "Activer le mode clair", "preferences.dark": "Activer le mode nuit", "preferences.night": "Nuit", "preferences.day": "Clair", "preferences.language": "Langue de l’interface", "preferences.french": "Français", "preferences.english": "English",
    "subject.active": "Matière active", "activity.concept": "Notion", "activity.reading": "Lecture", "activity.exercise": "Exercice", "activity.quiz": "Quiz", "activity.flashcard_review": "Révision",
    "status.current": "En cours", "status.toDo": "À faire", "status.completed": "Terminé", "status.ready": "Prêt", "status.indexing": "Indexation", "status.queued": "En file", "status.review": "À revoir", "status.mastered": "maîtrisé",
    "dashboard.kicker": "Votre atelier du jour", "dashboard.title": "Avancez avec une étape claire.", "dashboard.context": "Votre parcours est construit à partir de {subject} et de vos sources sélectionnées.", "dashboard.next": "Prochaine étape", "dashboard.stepNumber": "Étape {current} sur {total}", "dashboard.approx": "environ {minutes} min", "dashboard.openStep": "Ouvrir l’étape active", "dashboard.viewPath": "Voir le parcours", "dashboard.finished": "Votre parcours est terminé", "dashboard.finishedCopy": "Révisez vos notions ou créez un nouveau parcours.", "dashboard.welcome": "Bienvenue dans votre atelier", "dashboard.importFirst": "Importer un document", "dashboard.createPath": "Créer un parcours",
    "dashboard.path": "Parcours", "dashboard.stepsValidated": "{count} étapes validées", "dashboard.reviews": "À réviser", "dashboard.reviewReason": "rappel planifié par votre progression", "dashboard.noReview": "aucun rappel urgent", "dashboard.emptyReview": "Aucune révision urgente. Votre prochaine étape est le meilleur point de départ.", "dashboard.stable": "Notions stables", "dashboard.stableReason": "validées par rappels et exercices", "dashboard.sources": "Sources", "dashboard.documentsUsable": "{count} documents exploitables", "dashboard.remember": "À ne pas oublier", "dashboard.priorityReviews": "Révisions prioritaires", "dashboard.viewAll": "Tout voir", "dashboard.today": "Aujourd’hui", "dashboard.tomorrow": "Demain", "dashboard.consolidate": "À consolider", "dashboard.fragile": "Une notion fragile", "dashboard.difficulty": "{count} difficulté(s) récente(s). Une courte séance ciblée suffit.", "dashboard.practiceConcept": "S’entraîner sur cette notion", "dashboard.activeSources": "Sources actives", "dashboard.readyDocuments": "{count} documents prêts", "dashboard.sourceReason": "Vos réponses et activités sont ancrées dans les sources sélectionnées.", "dashboard.manageSources": "Gérer les sources",
    "path.kicker": "Mon parcours", "path.reference": "Votre repère", "path.complete": "{percent} % terminé", "path.validated": "{count} étapes validées sur {total}. Les étapes restent modifiables depuis le backend EduNexus.", "path.linked": "Parcours relié à vos documents importés.", "path.steps": "Étapes du parcours", "path.continue": "Continuez là où vous en êtes", "path.open": "Ouvrir l’activité", "path.markComplete": "Marquer comme terminé", "path.create": "Créer un parcours", "path.createTitle": "Nouveau parcours", "path.titlePlaceholder": "Titre du parcours…", "path.descriptionPlaceholder": "Description (optionnel)…", "path.createBtn": "Créer", "path.creating": "Création…", "path.selectOrCreate": "Sélectionnez ou créez un parcours pour commencer.", "path.addStep": "Ajouter une étape", "path.addStepTitle": "Nouvelle étape", "path.stepType": "Type d’activité", "path.stepTitle": "Titre de l’étape", "path.stepTitlePlaceholder": "Ex: Introduction à Python", "path.addBtn": "Ajouter", "path.noSteps": "Aucune étape. Ajoutez-en une pour commencer.", "path.deleteConfirm": "Supprimer ce parcours ?", "path.generateFromBooks": "Générer depuis mes livres", "path.selectBooks": "Sélectionner les livres", "path.generating": "Génération en cours…", "path.dragHint": "Glissez-déposez pour réordonner", "path.completedSteps": "{count} étapes terminées", "path.deleteStep": "Supprimer l’étape",
    "learning.kicker": "Réviser", "learning.title": "Une notion, une séance utile.", "learning.copy": "Comprenez, rappelez puis vérifiez. Les révisions sont proposées à partir de votre progression.", "learning.choose": "Choisir la notion", "learning.chooseCopy": "une difficulté ou une révision due", "learning.recall": "Faire un rappel", "learning.recallCopy": "sans regarder la réponse", "learning.check": "Vérifier et avancer", "learning.checkCopy": "avec un indice si nécessaire", "learning.current": "Notion en cours", "learning.mastery": "{score} % de maîtrise", "learning.change": "Changer de notion", "learning.scoreReason": "Votre score évolue avec les exercices et les rappels.", "learning.recallQuestion": "Question de rappel", "learning.recallPrompt": "Sans consulter vos notes, expliquez à quoi sert une boucle et dans quel cas vous choisiriez un `while`.", "learning.answerPlaceholder": "Écrivez votre réponse ou dictez-la…", "learning.checkReasoning": "Vérifier mon raisonnement", "learning.due": "Révisions dues", "learning.toDo": "{count} à faire", "learning.dueReason": "Une courte session maintenant aide à stabiliser la mémoire.", "learning.pathSteps": "Voir les étapes du parcours", "learning.audio": "Résumé audio local", "learning.reviewDifferently": "Réviser autrement", "learning.audioCopy": "Branchez cette carte au moteur TTS existant pendant l’intégration FastAPI.", "learning.prepareSummary": "Préparer le résumé", "learning.cards": "Fiches", "learning.spaced": "Rappel espacé", "learning.cardsReason": "{count} difficulté(s) récente(s) : utilisez les fiches proposées avant de passer à une nouvelle notion.",
    "library.kicker": "Mes sources", "library.title": "La base vérifiable de votre apprentissage.", "library.copy": "Les parcours, exercices et réponses du tuteur peuvent être reliés à ces documents.", "library.search": "Rechercher une source…", "library.add": "Ajouter une source", "library.queueReady": "File d’indexation prête", "library.queueWorking": "Indexation en cours", "library.waiting": "{count} document(s) en attente", "library.current": "Un document est traité", "library.queueReason": "{count} documents indexés pendant cette session. Le worker reste volontairement séquentiel.", "library.pause": "Mettre en pause", "library.start": "Démarrer la file", "library.active": "Bibliothèque active", "library.documents": "{count} documents", "library.provenance": "provenance conservée", "library.semanticSearch": "Recherche sémantique", "library.autoClassify": "Classer automatiquement", "library.importPanel": "Importer un document", "library.importDomain": "Domaine (existant ou nouveau)", "library.importDomainPlaceholder": "ex. Programmation", "library.importFile": "Fichier — TXT, MD, PDF, EPUB, DOCX, PPTX", "library.importBtn": "Importer et indexer", "library.importing": "Envoi du fichier…", "library.importDone": "Document importé.", "library.createCategory": "Créer une catégorie", "library.uncategorized": "Non classé", "library.renameCategory": "Renommer", "library.deleteCategory": "Supprimer", "library.deleteBook": "Supprimer le document", "library.reindex": "Réindexer", "library.searchTitle": "Rechercher dans les sources", "library.searchPlaceholder": "Votre question…", "library.searchBtn": "Rechercher", "library.searching": "Recherche…", "library.noResults": "Aucun fragment trouvé — élargissez la formulation.", "library.searchFailed": "La recherche a échoué.", "library.classifying": "Classification en cours…", "library.categoryRenamed": "Catégorie renommée.", "library.categoryDeleted": "Catégorie supprimée — documents conservés.", "library.bookDeleted": "Document supprimé.", "library.emptyLibrary": "Aucun domaine. Importez un premier document.", "library.dropHere": "Glissez-déposez un fichier ici", "library.orBrowse": "ou cliquez pour parcourir",
    "practice.kicker": "Exercices", "practice.title": "Entraînez une compétence précise.", "practice.copy": "Le niveau proposé part de votre maîtrise, puis évolue selon vos réponses.", "practice.prepare": "Préparer une séance", "practice.adaptive": "Exercice adaptatif", "practice.concept": "Notion", "practice.difficulty": "Difficulté", "practice.guided": "Guidé", "practice.adaptiveLevel": "Adaptatif", "practice.challenge": "Défi", "practice.advice": "Conseil.", "practice.guidedAdvice": "Commencez guidé : un indice au bon moment vaut mieux qu’une solution immédiate.", "practice.adaptiveAdvice": "Le niveau adaptatif est un bon prochain pas.", "practice.generate": "Générer un exercice", "practice.preview": "Aperçu de l’activité", "practice.previewTitle": "Construire une condition qui déclenche une action selon une valeur.", "practice.previewCopy": "Cette zone recevra l’énoncé, les indices gradués, la réponse de l’élève et le retour généré par l’API FastAPI.", "practice.source": "Source", "practice.duration": "Durée estimée", "practice.minutes": "12 min",
    "quiz.kicker": "Quiz", "quiz.title": "Mesurez un progrès, pas seulement un score.", "quiz.copy": "Choisissez une intention ; les questions seront ensuite sélectionnées dans les sources actives.", "quiz.launch": "Lancer une session", "quiz.goal": "Quel est votre objectif ?", "quiz.diagnostic": "Me situer", "quiz.diagnosticCopy": "Un quiz court pour identifier la prochaine notion.", "quiz.review": "Réviser", "quiz.reviewCopy": "Un rappel ciblé sur les révisions du jour.", "quiz.challenge": "Me challenger", "quiz.challengeCopy": "Une session plus exigeante pour vérifier les liens entre notions.", "quiz.duration": "Durée prévue", "quiz.prepare": "Préparer ce quiz", "quiz.trust": "Votre règle de confiance", "quiz.citation": "Chaque correction doit renvoyer à une source.", "quiz.citationCopy": "La couche API de migration est prête à afficher un livre, chapitre, page et extrait justificatif sous chaque réponse.", "quiz.ready": "Session prête", "quiz.readyCopy": "Le quiz peut commencer.", "quiz.connect": "Branchez l’action sur l’endpoint FastAPI de génération d’évaluation durant l’intégration.",
    "progress.kicker": "Progression", "progress.title": "Voyez ce qui progresse et ce qui mérite une courte séance.", "progress.copy": "La maîtrise est estimée à partir des rappels, exercices et évaluations réalisés dans cette matière.", "progress.path": "Progression du parcours", "progress.steps": "{count} étapes validées", "progress.stable": "Notions stables", "progress.stableReason": "après rappels et exercices", "progress.consolidate": "À consolider", "progress.consolidateReason": "selon vos dernières réponses", "progress.byConcept": "Par notion", "progress.map": "Votre carte de maîtrise", "progress.exercise": "Faire un exercice", "progress.nextReview": "Prochaine révision : {date}", "progress.new": "Nouvelle notion à découvrir",
    "tutor.kicker": "Tuteur IA", "tutor.defaultSubject": "votre matière", "tutor.title": "Posez une question dans le contexte de vos sources.", "tutor.copy": "Cette vue est prête à être reliée au WebSocket FastAPI existant pour les réponses en streaming.", "tutor.limited": "Réponses limitées aux sources actives", "tutor.question": "Quelle notion voulez-vous éclaircir ?", "tutor.questionCopy": "Essayez une question précise : « Comment choisir entre une boucle for et une boucle while ? »", "tutor.explain": "Expliquer avec un exemple", "tutor.ask": "Me questionner pas à pas", "tutor.messageReady": "Message préparé.", "tutor.messageCopy": "Connectez sendTutorMessage() à l’endpoint WebSocket lors de l’intégration pour afficher la réponse, les citations et les extraits.", "tutor.placeholder": "Écrivez une question sur vos sources…", "tutor.tip": "Bon réflexe", "tutor.askCitation": "Demandez une citation.", "tutor.citationReason": "Une réponse utile peut indiquer le livre, le chapitre et l’extrait qui l’appuient.", "tutor.mode": "Mode pédagogique", "tutor.hint": "Demander un indice.", "tutor.hintReason": "Le tuteur peut guider votre raisonnement avant d’afficher une réponse complète.",
    "settings.kicker": "Réglages", "settings.title": "Gardez le contrôle sur vos ressources et vos données.", "settings.copy": "Les paramètres ci-dessous sont structurés pour être reliés aux réglages persistants de FastAPI.", "settings.resources": "Ressources locales", "settings.models": "Indexation et modèles", "settings.modelsCopy": "Commencez avec un batch de 16 et une concurrence de 1 sur un ordinateur modeste.", "settings.batch": "Taille du batch", "settings.concurrency": "Concurrence maximale", "settings.automation": "Automatisations", "settings.night": "Travail de nuit", "settings.nightCopy": "La file traite les documents un par un et peut préparer des contenus pédagogiques après l’indexation.", "settings.nightWindow": "Activer la fenêtre nocturne", "settings.nightWindowCopy": "23:00 — 07:00, secteur uniquement", "settings.prepare": "Préparer les fiches et glossaires", "settings.prepareCopy": "Après une indexation réussie", "settings.maintenance": "Entretien local", "settings.library": "Bibliothèque et sauvegardes", "settings.libraryCopy": "Les contrôles d’intégrité et la sauvegarde SQLite restent pilotables depuis l’API de maintenance existante.", "settings.run": "Lancer la maintenance", "settings.save": "Enregistrer les réglages", "settings.saved": "Réglages enregistrés", "settings.privacy": "Confidentialité", "settings.local": "Vos données restent chez vous.", "settings.localCopy": "Le frontend n’ajoute aucun service cloud. Les connexions API sont configurées avec votre instance FastAPI locale.",
    "graph.kicker": "Graphe de compétences", "graph.title": "Visualisez les liens entre vos notions.", "graph.copy": "Le graphe relie les concepts de votre matière par des relations de prérequis et de dépendance.", "graph.build": "Construire le graphe", "graph.building": "Construction en cours…", "graph.empty": "Aucun graphe n'a encore été construit pour cette matière.", "graph.emptyCopy": "Lancez la construction pour générer les nœuds et les relations à partir de vos sources.", "graph.nodes": "Nœuds", "graph.edges": "Relations", "graph.nodeTitle": "Nœuds du graphe", "graph.edgeTitle": "Relations entre notions", "graph.mastery": "Maîtrise", "graph.confidence": "Confiance", "graph.confirmed": "Confirmé", "graph.unconfirmed": "Non confirmé", "graph.rejected": "Rejeté", "graph.validate": "Confirmer", "graph.validating": "Confirmation…", "graph.sourceNode": "Source", "graph.targetNode": "Cible", "graph.relation": "Relation", "graph.builtAt": "Construit le {date}",
    "subjectDash.kicker": "Tableau de bord", "subjectDash.title": "Vue d'ensemble de votre matière.", "subjectDash.copy": "Répartition des notions couvertes, manquantes, contradictoires et non confirmées.", "subjectDash.covered": "Couvertes", "subjectDash.coveredDesc": "Notions disposant de sources et de contenu.", "subjectDash.uncovered": "Non couvertes", "subjectDash.uncoveredDesc": "Notions sans source associée.", "subjectDash.contradictory": "Contradictoires", "subjectDash.contradictoryDesc": "Notions avec des informations conflictuelles.", "subjectDash.unconfirmed": "Non confirmées", "subjectDash.unconfirmedDesc": "Notions en attente de validation humaine.", "subjectDash.others": "+ {count} autres",     "subjectDash.empty": "Aucune donnée disponible.", "subjectDash.emptyCopy": "Construisez le graphe de compétences pour alimenter ce tableau de bord.",
    "profile.kicker": "Profil pédagogique", "profile.title": "Personnalisez l'apprentissage à votre objectif.", "profile.context": "Configurez le profil pédagogique de {subject} pour adapter exercices, quiz et parcours.", "profile.emptySubject": "Sélectionnez une matière dans le tableau de bord pour configurer votre profil pédagogique.", "profile.templates": "Modèles", "profile.templatesTitle": "Commencez avec un modèle prédéfini", "profile.noTemplates": "Aucun template disponible. Créez votre propre profil ci-dessous.", "profile.form": "Formulaire", "profile.formTitle": "Votre profil pédagogique", "profile.loadingProfile": "Chargement du profil…", "profile.domain": "Domaine", "profile.domainPlaceholder": "Ex : Programmation Python", "profile.level": "Niveau", "profile.levelPlaceholder": "Ex : Débutant, Intermédiaire, Avancé", "profile.objective": "Objectif", "profile.objectivePlaceholder": "Décrivez votre objectif d'apprentissage…", "profile.interpretGoal": "Interpréter un objectif", "profile.interpreting": "Interprétation en cours…", "profile.deadline": "Date limite", "profile.deadlinePlaceholder": "Ex : 2026-12-31", "profile.availableTime": "Temps disponible", "profile.availableTimePlaceholder": "Ex : 5h par semaine", "profile.explanationStyle": "Style d'explication", "profile.explanationStylePlaceholder": "Ex : Concis avec exemples concrets", "profile.activities": "Activités souhaitées (une par ligne)", "profile.activitiesPlaceholder": "Ex :\nExercices pratiques\nQuiz de validation\nLectures commentées", "profile.masteryCriteria": "Critères de maîtrise (un par ligne)", "profile.masteryCriteriaPlaceholder": "Ex :\nRésoudre un problème sans aide\nRéussir 3 quiz consécutifs\nExpliquer un concept à voix haute", "profile.save": "Enregistrer", "profile.saving": "Enregistrement…", "profile.saved": "Profil enregistré",
    "learners.kicker": "Apprenants", "learners.title": "Gérez les profils d'apprentissage.", "learners.context": "Créez, activez et supprimez des apprenants pour suivre leur progression individuellement.", "learners.create": "Créer", "learners.createTitle": "Nouvel apprenant", "learners.namePlaceholder": "Nom de l'apprenant…", "learners.creating": "Création…", "learners.addButton": "Créer un apprenant", "learners.list": "Liste", "learners.listTitle": "{count} apprenant(s)", "learners.loading": "Chargement des apprenants…", "learners.empty": "Aucun apprenant. Créez-en un pour commencer.", "learners.activeBadge": "Actif", "learners.createdAt": "Créé le {date}", "learners.activate": "Activer", "learners.deleteAria": "Supprimer {name}",
    "notebook.kicker": "Carnet de matière", "notebook.loading": "Chargement du carnet…", "notebook.retry": "Réessayer", "notebook.title": "Vos notes, sources et productions.", "notebook.copy": "Le carnet centralise les notes que vous ajoutez, les sources liées et les contenus générés par le tuteur.", "notebook.emptyTitle": "Votre carnet est vide.", "notebook.emptyCopy": "Ajoutez une première note ou lancez une action pour commencer à construire votre carnet de matière.", "notebook.notesSection": "Notes", "notebook.notesTitle": "{count} note(s)", "notebook.notePlaceholder": "Écrivez une note…", "notebook.addNote": "Ajouter une note", "notebook.noNotes": "Aucune note pour l'instant.", "notebook.sourcesSection": "Sources liées", "notebook.sourcesTitle": "{count} source(s)", "notebook.noSources": "Aucune source liée à ce carnet.", "notebook.actionSection": "Actions", "notebook.actionTitle": "Exploiter le carnet", "notebook.actionCopy": "Choisissez une action pour transformer vos notes et sources en contenu pédagogique.", "notebook.chooseAction": "Action à lancer", "notebook.runAction": "Lancer l'action", "notebook.action.summarize_source": "Résumer une source", "notebook.action.compare_chapters": "Comparer des chapitres", "notebook.action.create_study_sheet": "Créer une fiche de révision", "notebook.action.quiz_without_answer": "Quiz sans réponse", "notebook.action.explain_with_example": "Expliquer avec un exemple", "notebook.actionSummarize": "Résumer une source", "notebook.actionCompare": "Comparer des chapitres", "notebook.actionStudySheet": "Créer une fiche de révision", "notebook.actionQuiz": "Quiz sans réponse", "notebook.actionExplain": "Expliquer avec un exemple", "notebook.outputsSection": "Productions", "notebook.outputsTitle": "{count} production(s)", "notebook.deleteOutput": "Supprimer cette production", "notebook.noOutputs": "Aucune production pour l'instant.",
    "capture.kicker": "Capture de programme", "capture.loading": "Chargement du programme…", "capture.retry": "Réessayer", "capture.emptyTitle": "Aucun programme capturé.", "capture.emptyCopy": "Importez un fichier photo ou PDF pour extraire automatiquement l'arbre de compétences.", "capture.formSection": "Importer", "capture.formTitle": "Capturer un programme", "capture.filePath": "Chemin du fichier", "capture.pathPlaceholder": "/chemin/vers/programme.pdf", "capture.sourceType": "Type de source", "capture.typePdf": "PDF", "capture.typePhoto": "Photo", "capture.captureButton": "Capturer", "capture.programTitle": "Programme capturé", "capture.programCopy": "Vérifiez l'arbre de compétences extrait, corrigez si nécessaire puis confirmez le programme.", "capture.treeSection": "Arbre du programme", "capture.treeTitle": "{count} chapitre(s)", "capture.confirmed": "Confirmé", "capture.unconfirmed": "En attente", "capture.correct": "Corriger le titre", "capture.editTitle": "Modifier le titre", "capture.confirmProgram": "Confirmer le programme", "capture.newCapture": "Nouvelle capture", "capture.kind.chapter": "Chapitre", "capture.kind.sub_part": "Sous-partie", "capture.kind.competency": "Compétence", "capture.status.confirmed": "Confirmé", "capture.status.unconfirmed": "À vérifier", "capture.status.rejected": "Rejeté", "capture.generatePath": "Générer mon parcours",
  },
  en: {
    "nav.home": "Home", "nav.path": "My path", "nav.revise": "Review", "nav.practice": "Exercises", "nav.quiz": "Quiz", "nav.progress": "Progress", "nav.tutor": "AI tutor", "nav.sources": "My sources", "nav.settings": "Settings",
    "nav.start": "Start", "nav.train": "Practise", "nav.explore": "Explore", "nav.space": "Workspace",
    "app.workshop": "Learning workshop", "app.sourcesReady": "Your sources are ready", "app.localModel": "Local Ollama", "app.sources": "Sources", "app.localData": "Your data stays local.",
    "app.loadingSubject": "Loading your subject…", "app.loadingWorkshop": "Loading your learning workshop…", "nexus.aria": "Your sources feed concepts, which feed your next step.", "nexus.sources": "Sources", "nexus.concepts": "Concepts", "nexus.activeStep": "Active step",
    "preferences.light": "Switch to light mode", "preferences.dark": "Switch to night mode", "preferences.night": "Night", "preferences.day": "Light", "preferences.language": "Interface language", "preferences.french": "Français", "preferences.english": "English",
    "subject.active": "Active subject", "activity.concept": "Concept", "activity.reading": "Reading", "activity.exercise": "Exercise", "activity.quiz": "Quiz", "activity.flashcard_review": "Review",
    "status.current": "In progress", "status.toDo": "To do", "status.completed": "Completed", "status.ready": "Ready", "status.indexing": "Indexing", "status.queued": "Queued", "status.review": "To review", "status.mastered": "mastered",
    "dashboard.kicker": "Your learning workshop", "dashboard.title": "Move forward with one clear step.", "dashboard.context": "Your path is built from {subject} and the sources you selected.", "dashboard.next": "Next step", "dashboard.stepNumber": "Step {current} of {total}", "dashboard.approx": "about {minutes} min", "dashboard.openStep": "Open active step", "dashboard.viewPath": "View path", "dashboard.finished": "Your path is complete", "dashboard.finishedCopy": "Review your concepts or create a new learning path.", "dashboard.welcome": "Welcome to your workshop", "dashboard.importFirst": "Import a document", "dashboard.createPath": "Create a path",
    "dashboard.path": "Learning path", "dashboard.stepsValidated": "{count} validated steps", "dashboard.reviews": "To review", "dashboard.reviewReason": "scheduled from your learning progress", "dashboard.noReview": "no urgent review", "dashboard.emptyReview": "No urgent review. Your next step is the best place to start.", "dashboard.stable": "Stable concepts", "dashboard.stableReason": "validated through recall and practice", "dashboard.sources": "Sources", "dashboard.documentsUsable": "{count} usable documents", "dashboard.remember": "Do not forget", "dashboard.priorityReviews": "Priority reviews", "dashboard.viewAll": "View all", "dashboard.today": "Today", "dashboard.tomorrow": "Tomorrow", "dashboard.consolidate": "Strengthen", "dashboard.fragile": "One fragile concept", "dashboard.difficulty": "{count} recent difficulty point(s). A short focused session is enough.", "dashboard.practiceConcept": "Practise this concept", "dashboard.activeSources": "Active sources", "dashboard.readyDocuments": "{count} ready documents", "dashboard.sourceReason": "Your answers and activities are grounded in the sources you selected.", "dashboard.manageSources": "Manage sources",
    "path.kicker": "My learning path", "path.reference": "Your reference point", "path.complete": "{percent}% complete", "path.validated": "{count} validated steps out of {total}. Steps remain editable from the EduNexus backend.", "path.linked": "Path linked to your imported documents.", "path.steps": "Path steps", "path.continue": "Continue where you are", "path.open": "Open activity", "path.markComplete": "Mark as complete", "path.create": "Create a path", "path.createTitle": "New path", "path.titlePlaceholder": "Path title…", "path.descriptionPlaceholder": "Description (optional)…", "path.createBtn": "Create", "path.creating": "Creating…", "path.selectOrCreate": "Select or create a path to get started.", "path.addStep": "Add a step", "path.addStepTitle": "New step", "path.stepType": "Activity type", "path.stepTitle": "Step title", "path.stepTitlePlaceholder": "e.g. Introduction to Python", "path.addBtn": "Add", "path.noSteps": "No steps yet. Add one to get started.", "path.deleteConfirm": "Delete this path?", "path.generateFromBooks": "Generate from my books", "path.selectBooks": "Select books", "path.generating": "Generating…", "path.dragHint": "Drag and drop to reorder", "path.completedSteps": "{count} steps completed", "path.deleteStep": "Delete step", "path.noBooks": "No documents imported. Import books in the library first.",
    "learning.kicker": "Review", "learning.title": "One concept, one useful session.", "learning.copy": "Understand, recall, then check. Reviews are suggested from your learning progress.", "learning.choose": "Choose the concept", "learning.chooseCopy": "a difficulty or a due review", "learning.recall": "Recall", "learning.recallCopy": "without looking at the answer", "learning.check": "Check and move on", "learning.checkCopy": "with a hint when needed", "learning.current": "Current concept", "learning.mastery": "{score}% mastery", "learning.change": "Change concept", "learning.scoreReason": "Your score changes with exercises and recall.", "learning.recallQuestion": "Recall question", "learning.recallPrompt": "Without looking at your notes, explain what a loop is for and when you would choose a `while` loop.", "learning.answerPlaceholder": "Write or dictate your answer…", "learning.checkReasoning": "Check my reasoning", "learning.due": "Due reviews", "learning.toDo": "{count} to do", "learning.dueReason": "A short session now helps stabilize memory.", "learning.pathSteps": "View path steps", "learning.audio": "Local audio summary", "learning.reviewDifferently": "Review differently", "learning.audioCopy": "Connect this card to the existing TTS engine when integrating FastAPI.", "learning.prepareSummary": "Prepare summary", "learning.cards": "Flashcards", "learning.spaced": "Spaced recall", "learning.cardsReason": "{count} recent difficulty point(s): use the suggested cards before starting a new concept.",
    "library.kicker": "My sources", "library.title": "The verifiable foundation of your learning.", "library.copy": "Paths, exercises and tutor answers can be linked to these documents.", "library.search": "Search a source…", "library.add": "Add a source", "library.queueReady": "Indexing queue ready", "library.queueWorking": "Indexing in progress", "library.waiting": "{count} document(s) waiting", "library.current": "One document is being processed", "library.queueReason": "{count} documents indexed during this session. The worker remains intentionally sequential.", "library.pause": "Pause queue", "library.start": "Start queue", "library.active": "Active library", "library.documents": "{count} documents", "library.provenance": "provenance retained", "library.semanticSearch": "Semantic search", "library.autoClassify": "Auto-classify", "library.importPanel": "Import a document", "library.importDomain": "Domain (existing or new)", "library.importDomainPlaceholder": "e.g. Programming", "library.importFile": "File — TXT, MD, PDF, EPUB, DOCX, PPTX", "library.importBtn": "Import and index", "library.importing": "Sending file…", "library.importDone": "Document imported.", "library.createCategory": "Create category", "library.uncategorized": "Uncategorized", "library.renameCategory": "Rename", "library.deleteCategory": "Delete", "library.deleteBook": "Delete document", "library.reindex": "Re-index", "library.searchTitle": "Search in sources", "library.searchPlaceholder": "Your question…", "library.searchBtn": "Search", "library.searching": "Searching…", "library.noResults": "No fragments found — broaden your query.", "library.searchFailed": "Search failed.", "library.classifying": "Classification in progress…", "library.categoryRenamed": "Category renamed.", "library.categoryDeleted": "Category deleted — documents kept.", "library.bookDeleted": "Document deleted.", "library.emptyLibrary": "No domains. Import a first document.", "library.dropHere": "Drag and drop a file here", "library.orBrowse": "or click to browse",
    "practice.kicker": "Exercises", "practice.title": "Practise one precise skill.", "practice.copy": "The suggested level starts from your mastery, then changes with your answers.", "practice.prepare": "Prepare a session", "practice.adaptive": "Adaptive exercise", "practice.concept": "Concept", "practice.difficulty": "Difficulty", "practice.guided": "Guided", "practice.adaptiveLevel": "Adaptive", "practice.challenge": "Challenge", "practice.advice": "Tip.", "practice.guidedAdvice": "Start guided: a well-timed hint is better than an immediate solution.", "practice.adaptiveAdvice": "Adaptive level is a good next step.", "practice.generate": "Generate exercise", "practice.preview": "Activity preview", "practice.previewTitle": "Build a condition that triggers an action based on a value.", "practice.previewCopy": "This area will receive the prompt, progressive hints, learner answer and feedback generated by the FastAPI API.", "practice.source": "Source", "practice.duration": "Estimated duration", "practice.minutes": "12 min",
    "quiz.kicker": "Quiz", "quiz.title": "Measure progress, not only a score.", "quiz.copy": "Choose an intention; questions will then be selected from active sources.", "quiz.launch": "Start a session", "quiz.goal": "What is your goal?", "quiz.diagnostic": "Find my level", "quiz.diagnosticCopy": "A short quiz to identify the next concept.", "quiz.review": "Review", "quiz.reviewCopy": "Targeted recall for today’s reviews.", "quiz.challenge": "Challenge myself", "quiz.challengeCopy": "A more demanding session to check links between concepts.", "quiz.duration": "Expected duration", "quiz.prepare": "Prepare this quiz", "quiz.trust": "Your trust rule", "quiz.citation": "Every correction must point back to a source.", "quiz.citationCopy": "The migration API layer is ready to show a book, chapter, page and supporting excerpt under each answer.", "quiz.ready": "Session ready", "quiz.readyCopy": "The quiz can start.", "quiz.connect": "Connect this action to the FastAPI assessment endpoint during integration.",
    "progress.kicker": "Progress", "progress.title": "See what is improving and what needs a short session.", "progress.copy": "Mastery is estimated from recall, exercises and assessments completed in this subject.", "progress.path": "Path progress", "progress.steps": "{count} validated steps", "progress.stable": "Stable concepts", "progress.stableReason": "after recall and exercises", "progress.consolidate": "To strengthen", "progress.consolidateReason": "from your latest answers", "progress.byConcept": "By concept", "progress.map": "Your mastery map", "progress.exercise": "Do an exercise", "progress.nextReview": "Next review: {date}", "progress.new": "New concept to discover",
    "tutor.kicker": "AI tutor", "tutor.defaultSubject": "your subject", "tutor.title": "Ask a question in the context of your sources.", "tutor.copy": "This view is ready to connect to the existing FastAPI WebSocket for streaming responses.", "tutor.limited": "Answers limited to active sources", "tutor.question": "Which concept would you like to clarify?", "tutor.questionCopy": "Try a precise question: “How do I choose between a for loop and a while loop?”", "tutor.explain": "Explain with an example", "tutor.ask": "Question me step by step", "tutor.messageReady": "Message ready.", "tutor.messageCopy": "Connect sendTutorMessage() to the WebSocket endpoint during integration to display the response, citations and excerpts.", "tutor.placeholder": "Write a question about your sources…", "tutor.tip": "Good practice", "tutor.askCitation": "Ask for a citation.", "tutor.citationReason": "A useful answer can show the book, chapter and supporting excerpt.", "tutor.mode": "Teaching mode", "tutor.hint": "Ask for a hint.", "tutor.hintReason": "The tutor can guide your reasoning before displaying a complete answer.",
    "settings.kicker": "Settings", "settings.title": "Keep control of your resources and data.", "settings.copy": "The options below are structured to connect to persistent FastAPI settings.", "settings.resources": "Local resources", "settings.models": "Indexing and models", "settings.modelsCopy": "Start with a batch of 16 and concurrency of 1 on a modest computer.", "settings.batch": "Batch size", "settings.concurrency": "Maximum concurrency", "settings.automation": "Automations", "settings.night": "Night work", "settings.nightCopy": "The queue handles documents one at a time and can prepare learning resources after indexing.", "settings.nightWindow": "Enable night window", "settings.nightWindowCopy": "11:00 PM — 7:00 AM, AC power only", "settings.prepare": "Prepare flashcards and glossaries", "settings.prepareCopy": "After successful indexing", "settings.maintenance": "Local maintenance", "settings.library": "Library and backups", "settings.libraryCopy": "Integrity checks and SQLite backup remain controlled through the existing maintenance API.", "settings.run": "Run maintenance", "settings.save": "Save settings", "settings.saved": "Settings saved", "settings.privacy": "Privacy", "settings.local": "Your data stays with you.",     "settings.localCopy": "The frontend adds no cloud service. API connections use your local FastAPI instance.",
    "graph.kicker": "Competency graph", "graph.title": "See the links between your concepts.", "graph.copy": "The graph connects your subject's concepts through prerequisite and dependency relations.", "graph.build": "Build the graph", "graph.building": "Building…", "graph.empty": "No graph has been built for this subject yet.", "graph.emptyCopy": "Start a build to generate nodes and relations from your sources.", "graph.nodes": "Nodes", "graph.edges": "Relations", "graph.nodeTitle": "Graph nodes", "graph.edgeTitle": "Relations between concepts", "graph.mastery": "Mastery", "graph.confidence": "Confidence", "graph.confirmed": "Confirmed", "graph.unconfirmed": "Unconfirmed", "graph.rejected": "Rejected", "graph.validate": "Confirm", "graph.validating": "Confirming…", "graph.sourceNode": "Source", "graph.targetNode": "Target", "graph.relation": "Relation", "graph.builtAt": "Built on {date}",
    "subjectDash.kicker": "Dashboard", "subjectDash.title": "Overview of your subject.", "subjectDash.copy": "Breakdown of covered, missing, contradictory and unconfirmed concepts.", "subjectDash.covered": "Covered", "subjectDash.coveredDesc": "Concepts with sources and content.", "subjectDash.uncovered": "Uncovered", "subjectDash.uncoveredDesc": "Concepts without an associated source.", "subjectDash.contradictory": "Contradictory", "subjectDash.contradictoryDesc": "Concepts with conflicting information.", "subjectDash.unconfirmed": "Unconfirmed", "subjectDash.unconfirmedDesc": "Concepts awaiting human validation.", "subjectDash.others": "+ {count} more",     "subjectDash.empty": "No data available.", "subjectDash.emptyCopy": "Build the competency graph to populate this dashboard.",
    "profile.kicker": "Pedagogical profile", "profile.title": "Personalise learning to your objective.", "profile.context": "Configure the pedagogical profile of {subject} to adapt exercises, quizzes and paths.", "profile.emptySubject": "Select a subject on the dashboard to configure your pedagogical profile.", "profile.templates": "Templates", "profile.templatesTitle": "Start with a predefined template", "profile.noTemplates": "No template available. Create your own profile below.", "profile.form": "Form", "profile.formTitle": "Your pedagogical profile", "profile.loadingProfile": "Loading profile…", "profile.domain": "Domain", "profile.domainPlaceholder": "E.g. Python Programming", "profile.level": "Level", "profile.levelPlaceholder": "E.g. Beginner, Intermediate, Advanced", "profile.objective": "Objective", "profile.objectivePlaceholder": "Describe your learning objective…", "profile.interpretGoal": "Interpret a goal", "profile.interpreting": "Interpreting…", "profile.deadline": "Deadline", "profile.deadlinePlaceholder": "E.g. 2026-12-31", "profile.availableTime": "Available time", "profile.availableTimePlaceholder": "E.g. 5 hours per week", "profile.explanationStyle": "Explanation style", "profile.explanationStylePlaceholder": "E.g. Concise with concrete examples", "profile.activities": "Desired activities (one per line)", "profile.activitiesPlaceholder": "E.g.:\nPractical exercises\nValidation quiz\nCommented readings", "profile.masteryCriteria": "Mastery criteria (one per line)", "profile.masteryCriteriaPlaceholder": "E.g.:\nSolve a problem without help\nPass 3 consecutive quizzes\nExplain a concept aloud", "profile.save": "Save", "profile.saving": "Saving…", "profile.saved": "Profile saved",
    "learners.kicker": "Learners", "learners.title": "Manage learner profiles.", "learners.context": "Create, activate and delete learners to follow their progress individually.", "learners.create": "Create", "learners.createTitle": "New learner", "learners.namePlaceholder": "Learner name…", "learners.creating": "Creating…", "learners.addButton": "Create a learner", "learners.list": "List", "learners.listTitle": "{count} learner(s)", "learners.loading": "Loading learners…", "learners.empty": "No learners. Create one to get started.", "learners.activeBadge": "Active", "learners.createdAt": "Created on {date}", "learners.activate": "Activate", "learners.deleteAria": "Delete {name}",
    "notebook.kicker": "Subject notebook", "notebook.loading": "Loading notebook…", "notebook.retry": "Retry", "notebook.title": "Your notes, sources and outputs.", "notebook.copy": "The notebook gathers notes you add, linked sources and tutor-generated content.", "notebook.emptyTitle": "Your notebook is empty.", "notebook.emptyCopy": "Add a first note or run an action to start building your subject notebook.", "notebook.notesSection": "Notes", "notebook.notesTitle": "{count} note(s)", "notebook.notePlaceholder": "Write a note…", "notebook.addNote": "Add a note", "notebook.noNotes": "No notes yet.", "notebook.sourcesSection": "Linked sources", "notebook.sourcesTitle": "{count} source(s)", "notebook.noSources": "No sources linked to this notebook.", "notebook.actionSection": "Actions", "notebook.actionTitle": "Use the notebook", "notebook.actionCopy": "Choose an action to turn your notes and sources into learning content.", "notebook.chooseAction": "Action to run", "notebook.runAction": "Run action", "notebook.action.summarize_source": "Summarize a source", "notebook.action.compare_chapters": "Compare chapters", "notebook.action.create_study_sheet": "Create a study sheet", "notebook.action.quiz_without_answer": "Quiz without answer", "notebook.action.explain_with_example": "Explain with example", "notebook.actionSummarize": "Summarize a source", "notebook.actionCompare": "Compare chapters", "notebook.actionStudySheet": "Create a study sheet", "notebook.actionQuiz": "Quiz without answer", "notebook.actionExplain": "Explain with example", "notebook.outputsSection": "Outputs", "notebook.outputsTitle": "{count} output(s)", "notebook.deleteOutput": "Delete this output", "notebook.noOutputs": "No outputs yet.",
    "capture.kicker": "Program capture", "capture.loading": "Loading program…", "capture.retry": "Retry", "capture.emptyTitle": "No program captured.", "capture.emptyCopy": "Import a photo or PDF file to automatically extract the competency tree.", "capture.formSection": "Import", "capture.formTitle": "Capture a program", "capture.filePath": "File path", "capture.pathPlaceholder": "/path/to/program.pdf", "capture.sourceType": "Source type", "capture.typePdf": "PDF", "capture.typePhoto": "Photo", "capture.captureButton": "Capture", "capture.programTitle": "Captured program", "capture.programCopy": "Review the extracted competency tree, fix if needed, then confirm the program.", "capture.treeSection": "Program tree", "capture.treeTitle": "{count} chapter(s)", "capture.confirmed": "Confirmed", "capture.unconfirmed": "Pending", "capture.correct": "Correct the title", "capture.editTitle": "Edit title", "capture.confirmProgram": "Confirm program", "capture.newCapture": "New capture", "capture.kind.chapter": "Chapter", "capture.kind.sub_part": "Sub-part", "capture.kind.competency": "Competency", "capture.status.confirmed": "Confirmed", "capture.status.unconfirmed": "To verify", "capture.status.rejected": "Rejected", "capture.generatePath": "Generate my learning path",
  },
};

const isLocale = (value: string | null): value is Locale => value === "fr" || value === "en";
const isTheme = (value: string | null): value is Theme => value === "light" || value === "dark";
const queryPreferences = new URLSearchParams(window.location.search);
const storedLocale = localStorage.getItem("edunexus:locale");
const storedTheme = localStorage.getItem("edunexus:theme");
const requestedLocale = queryPreferences.get("lang");
const requestedTheme = queryPreferences.get("theme");
const locale = ref<Locale>(isLocale(storedLocale) ? storedLocale : isLocale(requestedLocale) ? requestedLocale : "fr");
const theme = ref<Theme>(isTheme(storedTheme) ? storedTheme : isTheme(requestedTheme) ? requestedTheme : window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");

function applyDocumentPreferences() {
  document.documentElement.lang = locale.value;
  document.documentElement.dataset.theme = theme.value;
  document.documentElement.style.colorScheme = theme.value;
  document.title = locale.value === "fr" ? "EduNexus — Mon parcours" : "EduNexus — My path";
}

function setLocale(nextLocale: Locale) {
  locale.value = nextLocale;
  localStorage.setItem("edunexus:locale", nextLocale);
  applyDocumentPreferences();
}

function toggleTheme() {
  theme.value = theme.value === "light" ? "dark" : "light";
  localStorage.setItem("edunexus:theme", theme.value);
  applyDocumentPreferences();
}

function t(key: string, values: Record<string, string | number> = {}) {
  const source = messages[locale.value][key] ?? messages.fr[key] ?? key;
  return Object.entries(values).reduce((result, [name, value]) => result.replaceAll(`{${name}}`, String(value)), source);
}

applyDocumentPreferences();

export function usePreferences() {
  return {
    locale,
    theme,
    isNight: computed(() => theme.value === "dark"),
    t,
    setLocale,
    toggleTheme,
  };
}
